version: "3.9"
services:
  caddy:
    image: caddy:2.3.0-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./frontend:/home/frontend
      - ./backend:/home/backend
    depends_on:
      - frontend
      - backend
    networks:
      - aspire_net

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    networks:
      - aspire_net

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./.env
    networks:
      - aspire_net

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    ports:
      - "8080:8080"
    working_dir: /usr/app/frontend/
    volumes:
      - ./frontend:/usr/app/frontend
    entrypoint: /bin/sh -c "yarn install && quasar dev"
    depends_on:
      - postgres
    networks:
      - aspire_net

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./.docker/backend/Dockerfile
    ports:
      - "8081:8081"
    working_dir: /usr/app/backend/
    depends_on:
      - postgres
      - frontend
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    networks:
      - aspire_net

networks:
  aspire_net:
    name: aspire_net
    driver: bridge


