version: "3.5"
services:
  postgres:
    image: postgres:11
    ports:
      - 5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - postgres
  server:
    build: .
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    restart: always
    depends_on:
      - postgres
